package edu.calpoly.csc366.teamdatabase.supplier;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.repository.query.Param;


public interface ShipmentRepository extends JpaRepository<Shipment, Long> {
    // query inferred from method name, code generated by Spring Framework
    Shipment findByTrackingNumber(String trackingNumber);

    // JPQL query  (validity check on application init)
    @Query("from Shipment s where s.trackingNumber = :trackingNumber")
    Supplier findByTrackingNumberJpql(@Param("trackingNumber") String trackingNumber);
}
