package edu.calpoly.csc366.teamdatabase.supplier;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.repository.query.Param;


public interface SupplierRepository extends JpaRepository<Supplier, Long> {
    // query inferred from method name, code generated by Spring Framework
    Supplier findByFirstName(String firstName);

    // JPQL query  (validity check on application init)
    @Query("from Supplier s where s.firstName = :name or s.lastName = :name")
    Supplier findByNameJpql(@Param("name") String name);
}
