package edu.calpoly.csc366.teamdatabase.manager;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.repository.query.Param;


// This class will be automatically implemented by Spring and made available as a "Bean" named personRepository
@Repository
public interface ManagerRepository extends JpaRepository<Manager, Long> {
    // query inferred from method name, code generated by Spring Framework
    Manager findByFirstName(String firstName);

    // JPQL query
    @Query("from Manager m where m.firstName = :name or m.lastName = :name")
    Manager findByNameJpql(@Param("name") String name);
}
