package edu.calpoly.csc366.teamdatabase.manager;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.repository.query.Param;


// This class will be automatically implemented by Spring and made available as a "Bean" named personRepository
@Repository
public interface ManagerRepository extends JpaRepository<Manager, Integer> {
    // query inferred from method name, code generated by Spring Framework
    Manager findByFirstName(String firstName);

    // JPQL query (validity check on application init)
    @Query("from Manager m where m.firstName = :name or m.lastName = :name")
    Manager findByNameJpql(@Param("name") String name);

    // JPQL query with join
    @Query("select m from Manager m join m.store store where m.firstName = :name or m.lastName = :name")
    Manager findByNameWithStoreJpql(@Param("name") String name);

    // Native SQL query  (validity not checked, invalid SQL will cause runtime exception)
    @Query(value = "select * from Manager m where m.first_anme = :name or m.last_name = :name", nativeQuery = true)
    Manager findByNameSql(@Param("name") String name);

    @Modifying
    @Query("update Manager m set m.firstName = :newName where m.firstName = :oldName")
    void updateName(@Param("oldName") String oldName, @Param("newName") String newName);
}
