package edu.calpoly.csc366.teamdatabase.manager;

import org.springframework.data.jpa.repository.JpaRepository;

public interface StoreRepository extends JpaRepository<Store, Long> {
    // query inferred from method name, code generated by Spring Framework
    Store findByStoreId(Integer id);
}
